# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x08payments\"l\n\x0ePaymentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0fsubscription_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x0e\n\x06method\x18\x05 \x01(\t\"5\n\x0fPaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"%\n\x0fValidateRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\"6\n\x10ValidateResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xa0\x01\n\x0ePaymentService\x12\x44\n\rRecordPayment\x12\x18.payments.PaymentRequest\x1a\x19.payments.PaymentResponse\x12H\n\x0fValidatePayment\x12\x19.payments.ValidateRequest\x1a\x1a.payments.ValidateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTREQUEST']._serialized_start=27
  _globals['_PAYMENTREQUEST']._serialized_end=135
  _globals['_PAYMENTRESPONSE']._serialized_start=137
  _globals['_PAYMENTRESPONSE']._serialized_end=190
  _globals['_VALIDATEREQUEST']._serialized_start=192
  _globals['_VALIDATEREQUEST']._serialized_end=229
  _globals['_VALIDATERESPONSE']._serialized_start=231
  _globals['_VALIDATERESPONSE']._serialized_end=285
  _globals['_PAYMENTSERVICE']._serialized_start=288
  _globals['_PAYMENTSERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
